"version"="Alpha v0.0.1"
"secretkey"="canada$God7972#"
"github-client-ID"="591780b1d345f5ff9be8"
"github-client-secret"="463765a931381f742918d3fc38b7e127ab6b908d"
"database"="Manavta"
"database-host"="mongodb://earthing:$Earthing1horse@manavta-shard-00-00.6gapz.mongodb.net:27017/Manavta?ssl=true&replicaSet=atlas-i2dc80-shard-0&authSource=admin&retryWrites=true&w=majority" 